--- 
- name: My Test Playbook
  hosts: all
  become: true 
  tasks:
   - name: create a users
     users: name='{{items}}' state=present 
     with_items:
       -  Raj 
       -  Sai
       -  hari
   
   
   
   

    
   
